from __future__ import annotations

from datetime import datetime
from html import escape
from typing import Any


def _safe_value(value: Any, default: str = "-") -> str:
    if value is None:
        return default
    return escape(str(value))


def render_header(external_id: str, published_at: datetime) -> str:
    return (
        "<h1>Payment Dispute Case Summary</h1>"
        f"<p><strong>Dispute External ID:</strong> {_safe_value(external_id)}<br/>"
        f"<strong>Published At:</strong> {_safe_value(published_at.isoformat())}</p>"
    )


def render_dispute_details(dispute: Any) -> str:
    return (
        "<h2>Dispute Details</h2>"
        "<table>"
        "<tbody>"
        f"<tr><td><strong>Status</strong></td><td>{_safe_value(getattr(dispute, 'status', None))}</td></tr>"
        f"<tr><td><strong>Type</strong></td><td>{_safe_value(getattr(dispute, 'type', None))}</td></tr>"
        f"<tr><td><strong>Amount</strong></td><td>{_safe_value(getattr(dispute, 'amount', None))} {_safe_value(getattr(dispute, 'currency', None), '')}</td></tr>"
        f"<tr><td><strong>Customer ID</strong></td><td>{_safe_value(getattr(dispute, 'customer_id', None))}</td></tr>"
        "</tbody>"
        "</table>"
    )


def render_resolution_notes(dispute: Any) -> str:
    return (
        "<h2>Resolution Notes</h2>"
        f"<p>{_safe_value(getattr(dispute, 'reason', None), 'No resolution notes were provided.')}</p>"
    )


def render_footer() -> str:
    return "<hr/><p><em>Generated by payment-dispute-backend automation.</em></p>"